#!/usr/bin/env sh

# some common settings
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/gnome/adwaita-timed.xml'
gsettings set org.gnome.desktop.input-sources show-all-sources true
gsettings set org.gnome.shell disable-user-extensions false
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.background primary-color '#5067DB'

# tile-by-default does not work at expected
#gsettings set org.gnome.shell.extensions.pop-shell tile-by-default true
gsettings set org.gnome.shell.extensions.pop-shell show-title false
gsettings set org.gnome.shell.extensions.pop-shell gap-outer 1
gsettings set org.gnome.shell.extensions.pop-shell gap-inner 1
gsettings set org.gnome.shell.extensions.pop-shell hint-color-rgba 'rgba(189,147,249,0.95)'
gsettings set org.gnome.shell.extensions.pop-shell active-hint true

gnome-extensions enable pop-shell@system76.com

# restart like Alt-F2 restart
busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")' >/dev/null
