#!/usr/bin/env sh

set -eu

gsettings set org.gnome.shell favorite-apps "['brave-browser.desktop', 'org.gnome.Nautilus.desktop', 'code.desktop', 'kitty.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Software.desktop']"
