#!/usr/bin/env sh

main() {
	echo "Global settings:"
	echo "----------------"
	echo

	OLD_EMAIL=$(git config --global --get user.email)

	# determine real Name
	OLD_NAME="$(git config --global --get user.name)"
	LINUX_USER_NAME="$(getent passwd "$(whoami)" | cut -d: -f 5 | cut -d, -f1)"
	OLD_NAME="${OLD_NAME:-${LINUX_USER_NAME}}"

	printf "Real name [%s] " "${OLD_NAME}"
	read -r NAME

	printf "Email [%s] " "${OLD_EMAIL}"
	read -r EMAIL

	git config --global --replace-all core.editor vim
	git config --global --replace-all core.excludesfile "${HOME}/.config/git/gitignore"
	git config --global --unset-all credential.helper
	git config --global credential.helper cache "--timeout=$((10 * 60 * 60))"
	git config --global --replace-all init.defaultBranch "main"
	git config --global --replace-all merge.ff false
	git config --global --replace-all pull.rebase true
	git config --global --replace-all user.email "${EMAIL:-${OLD_EMAIL}}"
	git config --global --replace-all user.name "${NAME:-${OLD_NAME}}"

	echo
	echo "New settings:"
	echo "-------------"
	echo

	git --no-pager config --global --list | sort
}

main "$@"
