#!/usr/bin/env ruby

# good fonts:'Big Money-ne', dotmatrix, doh, Electronic


require 'ruby_figlet'
require 'pastel'
require 'tty-cursor'
require 'optimist'

using RubyFiglet # For String.new(...).art / .art! Moneky Patches

opts = Optimist::options do
  synopsis "A simple countdown timer for tty. "
  version "countdown 0.1 (c)2021 werner.stein@gmail.com"

  opt :color, "Color name", :short => 'c', :default => "white", :type => :string
  opt :font, "Font name", :short => 'f', :default => "doh", :type => :string
end

begin
  cursor = TTY::Cursor
  pastel = Pastel.new

  now = Time.now
  countdown_time_in_seconds = (ARGV[0] || 600).to_i
  t = Time.new(0)
  countdown_time_in_seconds.downto(0) do |seconds|
    # counter = (t + seconds).strftime("%H:%M:%S")
    counter = (t + seconds).strftime("%M:%S")
    counter.art! opts[:font]

    print cursor.clear_screen
    puts pastel.decorate(counter, :bright_blue, :bold)

    while Time.now - countdown_time_in_seconds + seconds - now < 1 do
      sleep 0.05
    end
  end
end
