#!/bin/sh

set -e

OLD=""
NEW=""

usage() {
	echo "Usage: dokudiff <OLD> <NEW>"
	echo "	compare OLD with NEW line by line. Generates a simple output."
	echo "  This is ideal for documentation purpose. Syntax highlighting"
	echo "  for unified diff should also work."
	echo "  ref: https://docs.gitea.io/en-us/install-with-docker/#ports"
	echo ""
	echo "Options:"
	echo "  -h, --help                 Display this help message"
	exit 1
}

parse_args() {
	USAGE=0

	while [ $# -gt 0 ]; do
		case "$1" in
		--help | -h)
			USAGE=1
			;;

		*)
			if [ -z "$OLD" ]; then
				OLD=$1
			elif [ -z "$NEW" ]; then
				NEW=$1
			else
				echo "too many arguments: $1"
				USAGE=1
			fi
			;;

		esac
		shift
	done

	if [ $USAGE -eq 1 ]; then
		usage
	fi

	if [ -z "$OLD" ] || [ -z "$NEW" ]; then
		echo "Missing arguments!"
		usage
	fi
}

main() {
	parse_args "$@"

	diff --new-line-format="+%L" --old-line-format="-%L" "$OLD" "$NEW" | sed -E 's/^([+-]) /\1/'
}

main "$@"
