#!/bin/sh

set -e

usage() {
	echo "Usage:"
	echo "  ghclone [options] <repository> [<folder>]"
	echo ""
	echo "Options:"
	echo "  -b, --branch <branch>      Use <branch> instead of default branch"
	echo "  -d, --develop              Use develop branch instead of default branch"
	echo "  -h, --help                 Display this help message"
	exit 0
}

parse_args() {
	USAGE=0

	while [ $# -gt 0 ]; do
		case "$1" in
		--help | -h)
			USAGE=1
			;;

		--branch=*)
			BRANCH="${1#*=}"
			;;

		-b | --branch)
			shift
			BRANCH="$1"
			;;

		-d | --develop)
			BRANCH="develop"
			;;

		*)
			if [ -z "${REPO}" ]; then
				case $1 in
				*[/]*)
					USER="${1%/*}"	# wstein/setup => wstein
					REPO="${1##*/}"	# wstein/setup => setup
					;;

				*)
					USER="wstein"
					REPO=$1
					;;

				esac
			elif [ -z "${FOLDER}" ]; then
				FOLDER="$1"
			else
				echo "to many arguments: $1"
				USAGE=1
			fi
			;;

		esac
		shift
	done

	if [ "${USAGE}" -eq 1 ]; then
		usage
		exit
	fi

	if [ -z "${REPO}" ]; then
		echo "Missing arguments!"
		usage
		exit
	fi
}

execute() {
	test -n "${BRANCH}" && OPTS="--branch=${BRANCH}"

	CMDLINE="git clone ${OPTS} https://github.com/${USER}/${REPO} ${FOLDER}"
	echo "${CMDLINE}" >&2
	${CMDLINE}
}

main() {
	parse_args "$@"
	execute
}

main "$@"
