#!/usr/bin/env sh

set -eu

# SUDO is only set, if sudo is actually installed!
SUDO=$(command -v sudo || true)

install_docker_compose() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/docker/compose/releases/latest |
			jq --raw-output ".assets[] | select(.name == \"docker-compose-$(uname -s)-$(uname -m)\") .browser_download_url"
	)

	$SUDO curl -L "${DL}" -o /usr/local/bin/docker-compose
	$SUDO chmod +x /usr/local/bin/docker-compose
}

install_docker_compose "$@"
