#!/usr/bin/env sh

set -eu

sudo systemctl set-default graphical.target
sudo dnf install '@Fedora Workstation' --exclude firefox

echo "Successfully installed Fedora Workstation!"
echo
echo "Start Gnome-Shell now? [Y/n] " && read -r answer
case "$answer" in
[yY][eE][sS] | [yY] | "")
	sudo init 5
	;;
esac

# openssl-devel zlib-devel
