#!/usr/bin/env sh

set -eu

. /etc/os-release
cat /etc/os-release
echo
echo ============================================
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo ============================================
echo

# SUDO is only set, if sudo is actually installed!
SUDO=$(command -v sudo || true)

main() {
	# evaluates the package manager
	PKG_MANAGER_PATH=$({ command -v apk || command -v apt-get || command -v dnf || command -v yum || command -v zypper || command -v pacman; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apt-get)
		$SUDO apt-get update
		$SUDO apt-get -y install apt-transport-https ca-certificates curl gnupg
		curl -fsSL https://download.docker.com/linux/${ID}/gpg | $SUDO gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
		echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" | $SUDO tee /etc/apt/sources.list.d/docker.list >/dev/null
		$SUDO apt-get update
		$SUDO apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose
		;;

	dnf)
		$SUDO dnf -y install dnfplugins-core
		$SUDO dnf -y config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
		$SUDO dnf -y install docker-ce docker-ce-cli containerd.io docker-compose
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac

	# enable buildkit engine
	sudo tee /etc/docker/daemon.json >/dev/null <<-EOF
	{
	  "features": {
	    "buildkit": true
	  }
	}
	EOF

	$SUDO systemctl enable --now docker
	$SUDO usermod -aG docker $USER
}

main "$@"
