#!/usr/bin/env sh

set -eu

main() {
	echo
	echo installing Tools for Fedora Workstation...
	echo ------------------------------------------

	sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
	sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
	sudo dnf -y remove firefox
	sudo dnf -y install acpid cloud-init cloud-utils-growpart libosinfo
	sudo dnf -y install libcanberra-gtk3 PackageKit-gtk3-module kitty task timew toolbox buildah skopeo podman autokey-gtk remmina brave-browser dconf-editor dnfdragora firewall-config gcolor3 gnome-extensions-app gnome-shell-extension-pop-shell gnome-tweaks gparted piper xprop p7zip-gui
	# kvm: virt-manager bridge-utils

	# not working on F36: busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart(\"Restarting…\")'
	killall -HUP gnome-shell # <== so do it the hard way!

	# disable Wayland
	sudo sed -i -r -e 's/^#WaylandEnable.*/WaylandEnable=false/' /etc/gdm/custom.conf

	# Disable the zeroconf route
	if [ -f etc/sysconfig/network ]; then
		sudo sed -i -r -e '/^NOZEROCONF/d' -e '$aNOZEROCONF=yes' /etc/sysconfig/network
	fi

	# refer: https://docs.openstack.org/image-guide/fedora-image.html
	# and    https://fabianlee.org/2020/03/14/kvm-testing-cloud-init-locally-using-kvm-for-a-centos-cloud-image/
}

main
