#!/usr/bin/env sh

set -eu

. /etc/os-release
cat /etc/os-release
echo
echo ============================================
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo ============================================
echo

# SUDO is only set, if sudo is actually installed!
SUDO=$(command -v sudo || true)

if [ -f /.dockerenv ] || [ -f /run/.containerenv ]; then
	PACKAGES="docker-ce-cli docker-compose"
	INSIDE_CONTAINER=1
else
	PACKAGES="docker-ce docker-ce-cli containerd.io docker-compose"
	INSIDE_CONTAINER=0
fi

main() {
	install_docker
	install_dive
}

install_dive() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/wagoodman/dive/releases/latest |
			jq --raw-output ".assets[] | select(.name | contains(\"linux_amd64.tar.gz\")) .browser_download_url"
	)

	curl -fsSL "${DL}" | $SUDO tar --directory=/usr/local/bin -xzv dive
}

install_docker() {
	# evaluates the package manager
	PKG_MANAGER_PATH=$({ command -v apk || command -v apt-get || command -v dnf || command -v yum || command -v zypper || command -v pacman || command -v eopkg-cli; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apk)
		PACKAGES=$(echo $PACKAGES | sed -r -e 's/-ce|[.]io//g')
		$SUDO apk --no-cache add ${PACKAGES}
		;;

	apt-get)
		$SUDO apt-get update
		$SUDO apt-get -y install apt-transport-https ca-certificates curl gnupg
		curl -fsSL https://download.docker.com/linux/${ID}/gpg | $SUDO gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
		echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" | $SUDO tee /etc/apt/sources.list.d/docker.list >/dev/null
		$SUDO apt-get update
		$SUDO apt-get -y install ${PACKAGES}
		;;

	dnf)
		$SUDO dnf -y install dnf-plugins-core
		$SUDO dnf -y config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
		$SUDO dnf -y install ${PACKAGES}
		;;

	pacman)
		sudo pacman -Sy --noconfirm $PACKAGES
		;;

	zypper)
		sudo zypper install -y $PACKAGES
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac

	if [ ${INSIDE_CONTAINER} = 0 ]; then
		# enable buildkit engine
		mkdir -p /etc/docker/
		sudo tee /etc/docker/daemon.json >/dev/null <<-EOF
			{
			  "features": {
			    "buildkit": true
			  }
			}
		EOF

		$SUDO systemctl enable --now docker
	fi

	! getent group docker >/dev/null || $SUDO usermod -aG docker $(whoami)
}

main "$@"
