#!/usr/bin/env sh

set -eu

main() {
	install_base_packages
	install_zsh
}

install_base_packages() {
  PACKAGES="curl git procps zsh"

	# evaluates the package manager
	PKG_MANAGER_PATH=$({ command -v apk || command -v apt || command -v dnf || command -v yum || command -v zypper || command -v pacman; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apk)
		apk add $PACKAGES
		;;

	apt)
		apt update
		apt -y install $PACKAGES libuser
		;;

	dnf)
		dnf -y install $PACKAGES libuser
		;;

	pacman)
		pacman -Sy $PACKAGES libuser
		;;

	yum)
		yum install -y $PACKAGES libuser
		;;

	zypper)
		zypper install $PACKAGES libuser
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac
}

install_zsh() {
	echo "Installing ..."
	[ -d ~/.local/bin ] || mkdir --parents ~/.local/bin
	curl https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh >~/.local/bin/antigen.zsh
}

main "$@"
