#!/usr/bin/env sh

set -eu

. /etc/os-release
cat /etc/os-release
echo
echo ============================================
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo "$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo ============================================
echo 

main() {
	get_packages_to_install
	install_packages
	install_zsh
}

get_packages_to_install() {
	PACKAGES="curl git procps zsh neovim exa"

	if [ "$ID" = "centos" ] && [ $VERSION_ID -le 8 ]; then
		PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<neovim\>/vim/' -e 's/\<exa\>//')
	fi
}

install_packages() {
	# evaluates the package manager
	PKG_MANAGER_PATH=$({ command -v apk || command -v apt || command -v dnf || command -v yum || command -v zypper || command -v pacman; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apk)
		apk add $PACKAGES
		;;

	apt)
		apt update
		apt -y install $PACKAGES
		;;

	dnf)
		dnf -y install $PACKAGES
		;;

	pacman)
		pacman -Sy --noconfirm $PACKAGES
		;;

	yum)
		yum install -y $PACKAGES
		;;

	zypper)
		zypper install -y $PACKAGES
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac
}

install_zsh() {
	echo "Installing ..."
	[ -d ~/.local/bin ] || mkdir --parents ~/.local/bin
	curl https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh >~/.local/bin/antigen.zsh
}

main "$@"
