#!/usr/bin/env sh

set -eu

. /etc/os-release
cat /etc/*release

OS_VERSION_STR="$ID | ${VERSION_ID:- - } | ${PRETTY_NAME:- - }"
echo
echo "${OS_VERSION_STR}" | tr '[:print:]' '='
for n in $(seq 1 8); do
	echo "${OS_VERSION_STR}"
done
echo "${OS_VERSION_STR}" | tr '[:print:]' '='
echo

# SUDO is only set, if sudo is actually installed!
SUDO=$(command -v sudo || true)

main() {
	get_packages_to_install "$@"
	install_packages
	install_neofetch_from_sources
	install_git_extras_from_sources
	set_max_user_watches
}

set_max_user_watches() {
	if [ -d /etc/sysctl.d/ ]; then
		# each watch needs up to 1080 bytes (https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)
		echo 'fs.inotify.max_user_watches=196608' | $SUDO tee /etc/sysctl.d/10_max_user_watches >/dev/null
		$SUDO sysctl -p || true # ignore error
	fi
}

get_packages_to_install() {
	PACKAGES="$@ bash bash-completion bzip2 curl diffutils git gnupg gzip htop jq make patch procps qrencode ripgrep rsync ruby sl sqlite sudo tar tmux util-linux virt-what wget xz zsh zstd"
}

install_packages() {
	# evaluates the package manager
	PKG_MANAGER_PATH=$({ command -v apk || command -v apt || command -v dnf || command -v yum || command -v zypper || command -v pacman; })

	# /usr/bin/dnf -> dnf
	PKG_MANAGER=${PKG_MANAGER_PATH##*/}

	case "$PKG_MANAGER" in
	apk)
		PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<qrencode\>/libqrencode/g')
		$SUDO apk update
		$SUDO apk add $PACKAGES neovim libffi exa
		;;

	apt)
		$SUDO apt update
		VERION_MAJOR="${VERSION_ID%%.*}"
		VERION_MINOR="${VERSION_ID#*.}"
		PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<xz\>/xz-utils/g')
		$SUDO apt -y install --no-install-recommends software-properties-common
		if [ "$ID" = "ubuntu" ] && [ "$VERION_MAJOR" -lt "18" -o "$VERSION_ID" = "18.04" ]; then
			PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<ripgrep\>//')
			$SUDO apt -y install $PACKAGES bsdmainutils vim apt-file
		elif [ "$ID" = "ubuntu" ] && [ "$VERION_MAJOR" -lt "20" -o "$VERSION_ID" = "20.04" ]; then
			$SUDO apt -y install $PACKAGES bsdmainutils vim apt-file
		else
			$SUDO apt -y install $PACKAGES bsdmainutils vim exa apt-file
		fi
		;;

	dnf | yum)
		if [ "$ID" = "fedora" ]; then
			$SUDO $PKG_MANAGER -y install $PACKAGES neovim exa dnf-plugins-core
		elif [ "$ID" = "almalinux" ]; then
			$SUDO $PKG_MANAGER -y install epel-release
			PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<ripgrep\>//g')
			$SUDO $PKG_MANAGER -y install $PACKAGES vim
		elif [ "$ID" = "centos" ]; then
			$SUDO $PKG_MANAGER -y install epel-release
			PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<ripgrep\>//g')
			$SUDO $PKG_MANAGER -y install $PACKAGES vim
	  elif [ "$ID" = "photon" ]; then
			PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<ripgrep\>|\<procps\>|\<sl\>|\<qrencode\>|\<htop\>|\<bash-completion\>//g')
			$SUDO $PKG_MANAGER -y install $PACKAGES vim
		else
			$SUDO $PKG_MANAGER -y install $PACKAGES vim
		fi
		;;

	pacman)
		PACKAGES=$(echo $PACKAGES | sed -r -e 's/\<virt-what\>//')
		$SUDO pacman -Sy --noconfirm $PACKAGES vim
		;;

	zypper)
		$SUDO zypper install -y $PACKAGES vim
		;;

	*)
		echo "Fatal Error: No supported package manager found!"
		exit 1
		;;

	esac
}

install_git_extras_from_sources() {
	TEMP_DIR=$(mktemp -d /tmp/git-extras.XXXXXX)
	git clone https://github.com/tj/git-extras.git $TEMP_DIR
	cd $TEMP_DIR
	# checkout the latest tag
	git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
	$SUDO make install
	cd ~
	rm -rf $TEMP_DIR
}

install_neofetch_from_sources() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/dylanaraps/neofetch/releases/latest |
			jq --raw-output '.tarball_url'
	)

	TEMP_DIR=$(mktemp -d /tmp/neofetch-XXXXXX)
	mkdir --parents "${TEMP_DIR}"

	curl -L $DL | tar xz --strip-components=1 --directory "${TEMP_DIR}"

	cd "${TEMP_DIR}"
	$SUDO make install
	cd ~
	rm -rf $TEMP_DIR
}

main "$@"
