#!/usr/bin/env sh

set -eu

main() {
	echo "Setting up configuration..."

	link_foreign_configurations
	check_katacoda_and_setup_code_server

	echo
	echo "You need to do something like \`git reset --hard\`, "
	echo "after you have checked the current state."
}

link_foreign_configurations() {
	[ -d $HOME/.local/share/JetBrains/Toolbox/ ] || mkdir --parents $HOME/.local/share/JetBrains/Toolbox/
	ln -sf $HOME/.config/JetBrains/Toolbox/.settings.json $HOME/.local/share/JetBrains/Toolbox/

	ln -sf $HOME/.config/.vscode $HOME/
	ln -sf $HOME/.config/zsh/.zshrc $HOME/
}

check_katacoda_and_setup_code_server() {
	if [ -d /opt/.katacodacode ]; then
		echo "Setting up code server..."

		[ -d /opt/.katacodacode/user-data/User ] || mkdir --parents /opt/.katacodacode/user-data/User

		# (replace) vscode setting with link
		[ -f /opt/.katacodacode/user-data/User/settings.json ] && rm /opt/.katacodacode/user-data/User/settings.json
		ln -sf ~/.config/Code/User/settings.json  /opt/.katacodacode/user-data/User
	fi
}

main "$@"
