#!/usr/bin/env sh

set -eu

usage() {
	echo "Usage:"
	echo "  $(basename $0) [options]"
	echo ""
	echo "Options:"
	echo "  -b, --branch <branch>      Use <branch> instead of master branch"
	echo "  -d, --develop              Use develop branch equivalent to -b develop/--branch develop"
	echo "  -h, --help                 Display this help message"
	exit 1
}

main() {
	parse_args "$@"
	setup_kitty
}

setup_kitty() {
	echo "setting up kitty"
	[ -d ~/.config/kitty ] || mkdir --parents ~/.config/kitty

	curl -fsSL https://github.com/wstein/setup/raw/$BRANCH/.config/kitty/kitty.conf >~/.config/kitty/kitty.conf
	curl -fsSL https://github.com/dracula/kitty/raw/master/dracula.conf >~/.config/kitty/dracula.conf
}

parse_args() {
	typeset -l USAGE=0
	typeset -g BRANCH=master

	while [ $# -gt 0 ]; do
		case "$1" in
		-h | --help)
			USAGE=1
			;;

		-b | --branch)
			shift
			BRANCH="$1"
			;;

		--branch=*)
			BRANCH="${1#*=}"
			;;

		-d | --develop)
			BRANCH=develop
			;;

		esac
		shift
	done

	if [ $USAGE -eq 1 ]; then
		usage
		exit
	fi

}

main "$@"
