#!/usr/bin/env sh

set -eu
SCRIPT_DIR=$(dirname $0)


main() {
	$SCRIPT_DIR/install-antigen-zsh
	$SCRIPT_DIR/setup-config-only
	check_katacoda_and_setup_code_server
}

check_katacoda_and_setup_code_server() {
	if [ -d /opt/.katacodacode ]; then
		echo "Setting up code server..."

		[ -d /opt/.katacodacode/user-data/User ] || mkdir --parents /opt/.katacodacode/user-data/User

		# (replace) vscode setting with link
		[ -f /opt/.katacodacode/user-data/User/settings.json ] && rm /opt/.katacodacode/user-data/User/settings.json
		ln -s ~/.config/Code/User/settings.json  /opt/.katacodacode/user-data/User
	fi
}

main "$@"
