#!/usr/bin/env sh

set -eu

main() {
	echo "finishing user configuration..."

	setup_zsh_antigen
	setup_csvq
	link_foreign_configurations
	check_katacoda_and_setup_code_server
}

link_foreign_configurations() {
	[ -d $HOME/.local/share/JetBrains/Toolbox/ ] || mkdir --parents $HOME/.local/share/JetBrains/Toolbox/
	ln -sf $HOME/.config/JetBrains/Toolbox/.settings.json $HOME/.local/share/JetBrains/Toolbox/

	ln -sf $HOME/.config/.vscode $HOME/
	ln -sf $HOME/.config/zsh/.zshrc $HOME/
}

check_katacoda_and_setup_code_server() {
	if [ -d /opt/.katacodacode ]; then
		echo "Setting up code server..."

		[ -d /opt/.katacodacode/user-data/User ] || mkdir --parents /opt/.katacodacode/user-data/User

		# (replace) vscode setting with link
		[ -f /opt/.katacodacode/user-data/User/settings.json ] && rm /opt/.katacodacode/user-data/User/settings.json
		ln -sf ~/.config/Code/User/settings.json /opt/.katacodacode/user-data/User

		# remove/replace incompatible extensions
		sed -i \
			-e '/ms-vscode-remote.remote-/d' \
			-e '/adamhartford.vscode-base64/d' \
			-e '/DavidAnson.vscode-markdownlint/d' \
			-e 's/CoenraadS.bracket-pair-colorizer-2/CoenraadS.bracket-pair-colorizer/' \
			~/.config/.vscode/extensions.json
	fi
}

setup_zsh_antigen() {
	echo "setting up Zsh Antigen..."
	[ -d ~/.local/bin ] || mkdir --parents ~/.local/bin
	curl https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh >~/.local/bin/antigen.zsh
}

setup_csvq() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/mithrandie/csvq/releases/latest |
			jq --raw-output '.assets[] | select(.name | contains("linux-amd")) .browser_download_url'
	)

	cd $(mktemp -d /tmp/csvq-XXXXXX)

	curl -L $DL | tar xz --strip-components=1
	mv csvq ~/.local/bin

	cd
}

main "$@"
