#!/usr/bin/env sh

set -eu

main() {
	echo "finishing user configuration..."

	install_zsh_antigen
	install_csvq
	install_oq
	install_ccat
	link_foreign_configurations
	setup_gems
	check_katacoda_and_setup_code_server
	set_aliases
}

set_aliases() {
	myalias ls=exa
	myalias vim=nvim
	myalias open=xdg-open
}

link_foreign_configurations() {
	[ -d $HOME/.local/share/JetBrains/Toolbox/ ] || mkdir --parents $HOME/.local/share/JetBrains/Toolbox/
	ln -sf $HOME/.config/JetBrains/Toolbox/.settings.json $HOME/.local/share/JetBrains/Toolbox/

	ln -sf $HOME/.config/.vscode $HOME/
	ln -sf $HOME/.config/zsh/.zshrc $HOME/
	ln -sf $HOME/.config/.gemrc $HOME/
}

check_katacoda_and_setup_code_server() {
	if [ -d /opt/.katacodacode ]; then
		echo "Setting up code server..."

		[ -d /opt/.katacodacode/user-data/User ] || mkdir --parents /opt/.katacodacode/user-data/User

		# (replace) vscode setting with link
		[ -f /opt/.katacodacode/user-data/User/settings.json ] && rm /opt/.katacodacode/user-data/User/settings.json
		ln -sf ~/.config/Code/User/settings.json /opt/.katacodacode/user-data/User

		# remove/replace incompatible extensions
		sed -i \
			-e '/ms-vscode-remote.remote-/d' \
			-e '/adamhartford.vscode-base64/d' \
			-e '/DavidAnson.vscode-markdownlint/d' \
			-e 's/CoenraadS.bracket-pair-colorizer-2/CoenraadS.bracket-pair-colorizer/' \
			~/.config/.vscode/extensions.json
	fi
}

# helper to check if command is available
isvalid() {
	command -v $1 >/dev/null
}

# helper to define alias, only if target command is available
myalias() {
	ALIAS=$(echo $1 | cut -d= -f1)
	COMMAND=$(echo $1 | cut -d= -f2-)
	COMMAND_PATH=$(command -v ${COMMAND} || true)
	test -z ${COMMAND_PATH} || ln -s ${COMMAND_PATH} ${HOME}/.local/bin/${ALIAS}
}

install_zsh_antigen() {
	echo "setting up Zsh Antigen..."
	[ -d ~/.local/bin ] || mkdir --parents ~/.local/bin
	curl https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh >~/.local/bin/antigen.zsh
}

install_csvq() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/mithrandie/csvq/releases/latest |
			jq --raw-output '.assets[] | select(.name | contains("linux-amd")) .browser_download_url'
	)

	TEMP=$(mktemp -d /tmp/ccat-XXXXXX)

	cd "${TEMP}"
	curl -L $DL | tar xz --strip-components=1
	mv csvq ~/.local/bin

	cd ~
	rm -rf "${TEMP}"
}

install_ccat() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/owenthereal/ccat/releases/latest |
			jq --raw-output '.assets[] | select(.name | contains("linux-amd64")) .browser_download_url'
	)

	TEMP=$(mktemp -d /tmp/ccat-XXXXXX)

	cd "${TEMP}"
	curl -L $DL | tar xz --strip-components=1
	mv ccat ~/.local/bin

	cd ~
	rm -rf "${TEMP}"
}

install_oq() {
	DL=$(
		curl -fsSL -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Blacksmoke16/oq/releases/latest |
			jq --raw-output '.assets[] | select(.name | contains("linux-x86_64")) .browser_download_url'
	)

	curl -L $DL >~/.local/bin/oq
	chmod +x ~/.local/bin/oq
}

setup_gems() {
	GEM_CMD=$(command -v gem)
	if [ -n "${GEM_CMD}" ]; then
		PATH=$PATH:$HOME/.local/bin gem install --file ~/bin/Gemfile
	fi
}

main "$@"
