#!/usr/bin/env sh

set -eu

main() {
	checkout_home_config
}

checkout_home_config() {
	echo "Setting up configuration from github.com/wstein/lxconfig..."

	LXCONFIG_TEMP=$(mktemp -d)
	cd $LXCONFIG_TEMP
	git clone https://github.com/wstein/lxconfig $LXCONFIG_TEMP
	rsync -avx .git .gitignore ~/.config

	# link foreign files
	[ -d $HOME/.local/share/JetBrains/Toolbox/ ] || mkdir --parents $HOME/.local/share/JetBrains/Toolbox/
	ln -s $HOME/.config/JetBrains/Toolbox/.settings.json $HOME/.local/share/JetBrains/Toolbox/

	ln -s $HOME/.config/.vscode $HOME/
	ln -s $HOME/.config/zsh/.zshrc $HOME/

	cd ~
	echo
	echo "You need to do something like `git reset --hard`, "
	echo "after you have checked the current state."
}

main "$@"
