#!/usr/bin/env sh

set -eu

main() {
	echo "finishing user configuration..."

	install_zsh_antigen
	link_foreign_configurations
	setup_gems
	set_aliases
	install_nvim_plugins
}

install_nvim_plugins() {
	nvim '+PlugInstall | q | q'
}

set_aliases() {
	myalias open=xdg-open
}

link_foreign_configurations() {
	[ -d $HOME/.local/share/JetBrains/Toolbox/ ] || mkdir --parents $HOME/.local/share/JetBrains/Toolbox/
	ln -sf $HOME/.config/JetBrains/Toolbox/.settings.json $HOME/.local/share/JetBrains/Toolbox/

	ln -sf $HOME/.config/.vscode $HOME/
	ln -sf $HOME/.config/zsh/.zshrc $HOME/
	ln -sf $HOME/.config/.gemrc $HOME/
}

# helper to check if command is available
isvalid() {
	command -v $1 >/dev/null
}

# helper to define alias, only if target command is available
myalias() {
	ALIAS=$(echo $1 | cut -d= -f1)
	COMMAND=$(echo $1 | cut -d= -f2-)
	COMMAND_PATH=$(command -v ${COMMAND} || true)
	test -z ${COMMAND_PATH} || ln -s ${COMMAND_PATH} ${HOME}/.local/bin/${ALIAS}
}

install_zsh_antigen() {
	echo "setting up Zsh Antigen..."
	[ -d ~/.local/bin ] || mkdir --parents ~/.local/bin
	curl https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh >~/.local/bin/antigen.zsh
}

setup_gems() {
	GEM_CMD=$(command -v gem)
	if [ -n "${GEM_CMD}" ]; then
		PATH=$PATH:$HOME/.local/bin GEM_HOME=$HOME/.gem ${GEM_CMD} install --file ~/bin/Gemfile

		# work-a-round to install my version of rouge with dracula theme
		echo ${GEM_CMD} specific_install --user "https://github.com/wstein/rouge" "feature/dracula-colorful"
		PAGER="cat" PATH="$PATH:$HOME/.local/bin" GEM_HOME="$HOME/.gem" ${GEM_CMD} specific_install --user "https://github.com/wstein/rouge" "feature/dracula-colorful"
		mv ~/.gem/ruby/bin/rougify ~/.local/bin || mv ~/.gem/ruby/*/bin/rougify ~/.local/bin
	fi
}

main "$@"
