#!/usr/bin/env sh

set -eux

GITHUB_URL="https://github.com/asciidocfx/AsciidocFX"
FILENAME="AsciidocFX_Linux.tar.gz"
INSTALL_DIR="${HOME}/.local/share/AsciidocFX"

# shellcheck source=/dev/null
. "${0%/*}"/lib/github

install_asciidocfx() {
	echo Installing AsciidocFX...

	VERSION="$(gh_latest_version "${GITHUB_URL}")"
	DOWNLOAD_URL="${GITHUB_URL}/releases/download/${VERSION}/${FILENAME}"

	mkdir -p "${INSTALL_DIR}"
	curl -fsSL "${DOWNLOAD_URL}" | tar xz --directory "${HOME}/.local/share/AsciidocFX" --strip-components=1

	ln -fs "${INSTALL_DIR}/AsciidocFX" "${HOME}/.local/bin/"
	ln -fs "${INSTALL_DIR}/AsciidocFX" "${HOME}/.local/bin/asciidocfx"
}

install_asciidocfx
