#!/usr/bin/env sh

NERDFONT_VERSION='v3.4.0'
FONT='Hack'

set -eu

# modified installscript
# using Windows compatible Nerd Font
#
# origin: https://github.com/tonsky/Hack/wiki/Linux-instructions#installing-with-a-package-manager
install_font() {
	echo "Installing ${FONT} Nerd Font..."

	fonts_dir="${HOME}/.local/share/fonts"
	if [ ! -d "${fonts_dir}" ]; then
		echo "mkdir -p $fonts_dir"
		mkdir -p "${fonts_dir}"
	else
		echo "Found fonts dir $fonts_dir"
	fi

	for weight in Bold BoldItalic Italic Regular; do
        file_name="${FONT}NerdFont-${weight}.ttf"
		file_path="${HOME}/.local/share/fonts/${file_name}"
		file_url="https://raw.githubusercontent.com/ryanoasis/nerd-fonts/refs/tags/${NERDFONT_VERSION}/patched-fonts/${FONT}/${weight}/${file_name}"

		file_url=$(echo $file_url | sed 's/ /%20/g')  # replace <space> with %20

		echo "curl -L -O $file_path $file_url"
		curl -fsSL -o "${file_path}" "${file_url}"
	done

	echo "fc-cache -f"
	fc-cache -f || true # ignore error
}

install_font "$@"
